#############################################################################
# Makefile for building: tuxcards
# Generated by qmake (2.01a) (Qt 4.5.0) on: Tue Jan 18 13:50:56 2011
# Project:  tuxcards.pro
# Template: app
# Command: c:\DevTools\Qt\qt\bin\qmake.exe -win32 -o Makefile tuxcards.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DUNICODE -DQT_LARGEFILE_SUPPORT -DQT_NO_DEBUG -DQT_QT3SUPPORT_LIB -DQT3_SUPPORT -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_THREAD_SUPPORT
CFLAGS        = -O2 $(DEFINES)
CXXFLAGS      = -O2 $(DEFINES)
INCPATH       = -I"..\..\..\..\DevTools\Qt\qt\include\QtCore" -I"..\..\..\..\DevTools\Qt\qt\include\QtGui" -I"..\..\..\..\DevTools\Qt\qt\include\QtXml" -I"..\..\..\..\DevTools\Qt\qt\include\Qt3Support" -I"..\..\..\..\DevTools\Qt\qt\include" -I"..\..\..\..\DevTools\Qt\qt\include\ActiveQt" -I"." -I"..\..\..\..\DevTools\Qt\qt\mkspecs\win32-g++"
LINK        =        g++
LFLAGS        =        -enable-stdcall-fixup -Wl,-enable-auto-import -Wl,-enable-runtime-pseudo-reloc -Wl,-s
LIBS        =        -L"c:\DevTools\Qt\qt\lib" -lQt3Support4 -lQtXml4 -lQtGui4 -lQtCore4
QMAKE         = c:\DevTools\Qt\qt\bin\qmake.exe
IDC           = c:\DevTools\Qt\qt\bin\idc.exe
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
DEL_FILE      = del
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
INSTALL_FILE    = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR     = $(COPY_DIR)

####### Output directory

OBJECTS_DIR   = . 

####### Files

SOURCES       = src\persister.cpp \
		src\fontsettings.cpp \
		src\CTuxCardsConfiguration.cpp \
		src\commandlineoptions.cpp \
		src\gui\dialogs\CFileEncryptionPasswordDialog.cpp \
		src\main.cpp \
		src\gui\CTreeElement.cpp \
		src\gui\CTree.cpp \
		src\gui\mainwindow.cpp \
		src\gui\editor.cpp \
		src\gui\CSingleEntryView.cpp \
		src\gui\BookmarkButton.cpp \
		src\gui\RecentFileList.cpp \
		src\gui\dialogs\searchposition.cpp \
		src\gui\dialogs\searchlistitem.cpp \
		src\gui\dialogs\searchdialog.cpp \
		src\gui\dialogs\optionsdialog.cpp \
		src\gui\dialogs\iconselectordialog.cpp \
		src\gui\dialogs\iconselector.cpp \
		src\gui\dialogs\CPropertyDialog.cpp \
		src\gui\dialogs\CPasswdDialog.cpp \
		src\information\xmlpersister.cpp \
		src\information\Path.cpp \
		src\information\informationformat.cpp \
		src\information\htmlwriter.cpp \
		src\information\CTreeInformationElement.cpp \
		src\information\converter.cpp \
		src\information\CInformationElementHistory.cpp \
		src\information\CInformationElement.cpp \
		src\information\CInformationCollection.cpp \
		src\utilities\strings.cpp \
		src\utilities\integers.cpp \
		src\utilities\CIconManager.cpp \
		src\utilities\crypt\StringCrypter.cpp \
		src\utilities\crypt\MD5.cpp \
		src\utilities\crypt\BlowFish.cpp \
		src\utilities\iniparser\configparser.cpp \
		src\utilities\iniparser\configgroup.cpp moc_searchdialog.cpp \
		moc_optionsdialog.cpp \
		moc_iconselectordialog.cpp \
		moc_iconselector.cpp \
		moc_CPropertyDialog.cpp \
		moc_CPasswdDialog.cpp \
		moc_CFileEncryptionPasswordDialog.cpp \
		moc_CInformationElement.cpp \
		moc_CInformationCollection.cpp \
		moc_mainwindow.cpp \
		moc_editor.cpp \
		moc_CTree.cpp \
		moc_CSingleEntryView.cpp \
		moc_BookmarkButton.cpp \
		moc_RecentFileList.cpp \
		moc_CTreeElement.cpp
OBJECTS       = persister.o \
		fontsettings.o \
		CTuxCardsConfiguration.o \
		commandlineoptions.o \
		CFileEncryptionPasswordDialog.o \
		main.o \
		CTreeElement.o \
		CTree.o \
		mainwindow.o \
		editor.o \
		CSingleEntryView.o \
		BookmarkButton.o \
		RecentFileList.o \
		searchposition.o \
		searchlistitem.o \
		searchdialog.o \
		optionsdialog.o \
		iconselectordialog.o \
		iconselector.o \
		CPropertyDialog.o \
		CPasswdDialog.o \
		xmlpersister.o \
		Path.o \
		informationformat.o \
		htmlwriter.o \
		CTreeInformationElement.o \
		converter.o \
		CInformationElementHistory.o \
		CInformationElement.o \
		CInformationCollection.o \
		strings.o \
		integers.o \
		CIconManager.o \
		StringCrypter.o \
		MD5.o \
		BlowFish.o \
		configparser.o \
		configgroup.o \
		moc_searchdialog.o \
		moc_optionsdialog.o \
		moc_iconselectordialog.o \
		moc_iconselector.o \
		moc_CPropertyDialog.o \
		moc_CPasswdDialog.o \
		moc_CFileEncryptionPasswordDialog.o \
		moc_CInformationElement.o \
		moc_CInformationCollection.o \
		moc_mainwindow.o \
		moc_editor.o \
		moc_CTree.o \
		moc_CSingleEntryView.o \
		moc_BookmarkButton.o \
		moc_RecentFileList.o \
		moc_CTreeElement.o
DIST          = 
QMAKE_TARGET  = tuxcards
DESTDIR        =  #avoid trailing-slash linebreak
TARGET         = tuxcards.exe
DESTDIR_TARGET = tuxcards.exe

####### Implicit rules

.SUFFIXES: .cpp .cc .cxx .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

first: all
all: Makefile  $(DESTDIR_TARGET)

$(DESTDIR_TARGET):  $(OBJECTS) 
	$(LINK) $(LFLAGS) -o $(DESTDIR_TARGET) object_script.tuxcards  $(LIBS)


Makefile: tuxcards.pro  ../../../../DevTools/Qt/qt/mkspecs/win32-g++/qmake.conf ../../../../DevTools/Qt/qt/mkspecs/qconfig.pri \
		../../../../DevTools/Qt/qt/mkspecs/features/qt_functions.prf \
		../../../../DevTools/Qt/qt/mkspecs/features/qt_config.prf \
		../../../../DevTools/Qt/qt/mkspecs/features/exclusive_builds.prf \
		../../../../DevTools/Qt/qt/mkspecs/features/default_pre.prf \
		../../../../DevTools/Qt/qt/mkspecs/features/win32/default_pre.prf \
		../../../../DevTools/Qt/qt/mkspecs/features/release.prf \
		../../../../DevTools/Qt/qt/mkspecs/features/default_post.prf \
		../../../../DevTools/Qt/qt/mkspecs/features/win32/default_post.prf \
		../../../../DevTools/Qt/qt/mkspecs/features/qt.prf \
		../../../../DevTools/Qt/qt/mkspecs/features/win32/thread.prf \
		../../../../DevTools/Qt/qt/mkspecs/features/moc.prf
	$(QMAKE) -win32 -o Makefile tuxcards.pro
..\..\..\..\DevTools\Qt\qt\mkspecs\qconfig.pri:
..\..\..\..\DevTools\Qt\qt\mkspecs\features\qt_functions.prf:
..\..\..\..\DevTools\Qt\qt\mkspecs\features\qt_config.prf:
..\..\..\..\DevTools\Qt\qt\mkspecs\features\exclusive_builds.prf:
..\..\..\..\DevTools\Qt\qt\mkspecs\features\default_pre.prf:
..\..\..\..\DevTools\Qt\qt\mkspecs\features\win32\default_pre.prf:
..\..\..\..\DevTools\Qt\qt\mkspecs\features\release.prf:
..\..\..\..\DevTools\Qt\qt\mkspecs\features\default_post.prf:
..\..\..\..\DevTools\Qt\qt\mkspecs\features\win32\default_post.prf:
..\..\..\..\DevTools\Qt\qt\mkspecs\features\qt.prf:
..\..\..\..\DevTools\Qt\qt\mkspecs\features\win32\thread.prf:
..\..\..\..\DevTools\Qt\qt\mkspecs\features\moc.prf:
qmake:  FORCE
	@$(QMAKE) -win32 -o Makefile tuxcards.pro

dist:
	$(ZIP) tuxcards.zip $(SOURCES) $(DIST) tuxcards.pro ..\..\..\..\DevTools\Qt\qt\mkspecs\qconfig.pri ..\..\..\..\DevTools\Qt\qt\mkspecs\features\qt_functions.prf ..\..\..\..\DevTools\Qt\qt\mkspecs\features\qt_config.prf ..\..\..\..\DevTools\Qt\qt\mkspecs\features\exclusive_builds.prf ..\..\..\..\DevTools\Qt\qt\mkspecs\features\default_pre.prf ..\..\..\..\DevTools\Qt\qt\mkspecs\features\win32\default_pre.prf ..\..\..\..\DevTools\Qt\qt\mkspecs\features\release.prf ..\..\..\..\DevTools\Qt\qt\mkspecs\features\default_post.prf ..\..\..\..\DevTools\Qt\qt\mkspecs\features\win32\default_post.prf ..\..\..\..\DevTools\Qt\qt\mkspecs\features\qt.prf ..\..\..\..\DevTools\Qt\qt\mkspecs\features\win32\thread.prf ..\..\..\..\DevTools\Qt\qt\mkspecs\features\moc.prf  HEADERS SOURCES OBJECTIVE_SOURCES 

clean: compiler_clean 
	-$(DEL_FILE) persister.o fontsettings.o CTuxCardsConfiguration.o commandlineoptions.o CFileEncryptionPasswordDialog.o main.o CTreeElement.o CTree.o mainwindow.o editor.o CSingleEntryView.o BookmarkButton.o RecentFileList.o searchposition.o searchlistitem.o searchdialog.o optionsdialog.o iconselectordialog.o iconselector.o CPropertyDialog.o CPasswdDialog.o xmlpersister.o Path.o informationformat.o htmlwriter.o CTreeInformationElement.o converter.o CInformationElementHistory.o CInformationElement.o CInformationCollection.o strings.o integers.o CIconManager.o StringCrypter.o MD5.o BlowFish.o configparser.o configgroup.o moc_searchdialog.o moc_optionsdialog.o moc_iconselectordialog.o moc_iconselector.o moc_CPropertyDialog.o moc_CPasswdDialog.o moc_CFileEncryptionPasswordDialog.o moc_CInformationElement.o moc_CInformationCollection.o moc_mainwindow.o moc_editor.o moc_CTree.o moc_CSingleEntryView.o moc_BookmarkButton.o moc_RecentFileList.o moc_CTreeElement.o

distclean: clean
	-$(DEL_FILE) $(DESTDIR_TARGET)
	-$(DEL_FILE) Makefile

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_searchdialog.cpp moc_optionsdialog.cpp moc_iconselectordialog.cpp moc_iconselector.cpp moc_CPropertyDialog.cpp moc_CPasswdDialog.cpp moc_CFileEncryptionPasswordDialog.cpp moc_CInformationElement.cpp moc_CInformationCollection.cpp moc_mainwindow.cpp moc_editor.cpp moc_CTree.cpp moc_CSingleEntryView.cpp moc_BookmarkButton.cpp moc_RecentFileList.cpp moc_CTreeElement.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_searchdialog.cpp moc_optionsdialog.cpp moc_iconselectordialog.cpp moc_iconselector.cpp moc_CPropertyDialog.cpp moc_CPasswdDialog.cpp moc_CFileEncryptionPasswordDialog.cpp moc_CInformationElement.cpp moc_CInformationCollection.cpp moc_mainwindow.cpp moc_editor.cpp moc_CTree.cpp moc_CSingleEntryView.cpp moc_BookmarkButton.cpp moc_RecentFileList.cpp moc_CTreeElement.cpp
moc_searchdialog.cpp: src/gui/dialogs/searchlistitem.h \
		src/gui/dialogs/searchposition.h \
		src/gui/CTreeElement.h \
		src/information/CTreeInformationElement.h \
		src/information/CInformationElement.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/information/informationformat.h \
		src/global.h \
		src/information/Path.h \
		src/gui/dialogs/searchdialog.h
	C:/DevTools/Qt/qt/bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\gui\dialogs\searchdialog.h -o moc_searchdialog.cpp

moc_optionsdialog.cpp: ui_IOptionsDialog.h \
		src/CTuxCardsConfiguration.h \
		src/fontsettings.h \
		src/gui/dialogs/optionsdialog.h
	C:/DevTools/Qt/qt/bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\gui\dialogs\optionsdialog.h -o moc_optionsdialog.cpp

moc_iconselectordialog.cpp: src/gui/dialogs/iconselectordialog.h
	C:/DevTools/Qt/qt/bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\gui\dialogs\iconselectordialog.h -o moc_iconselectordialog.cpp

moc_iconselector.cpp: src/gui/dialogs/iconselector.h
	C:/DevTools/Qt/qt/bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\gui\dialogs\iconselector.h -o moc_iconselector.cpp

moc_CPropertyDialog.cpp: ui_IPropertyDialog.h \
		src/gui/dialogs/iconselectordialog.h \
		src/gui/dialogs/CPropertyDialog.h
	C:/DevTools/Qt/qt/bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\gui\dialogs\CPropertyDialog.h -o moc_CPropertyDialog.cpp

moc_CPasswdDialog.cpp: src/global.h \
		ui_IPasswdDialog.h \
		src/gui/dialogs/CPasswdDialog.h
	C:/DevTools/Qt/qt/bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\gui\dialogs\CPasswdDialog.h -o moc_CPasswdDialog.cpp

moc_CFileEncryptionPasswordDialog.cpp: src/global.h \
		ui_IFileEncryptionPasswordDialog.h \
		src/gui/dialogs/CFileEncryptionPasswordDialog.h
	C:/DevTools/Qt/qt/bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\gui\dialogs\CFileEncryptionPasswordDialog.h -o moc_CFileEncryptionPasswordDialog.cpp

moc_CInformationElement.cpp: src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/information/informationformat.h \
		src/information/CInformationElement.h
	C:/DevTools/Qt/qt/bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\information\CInformationElement.h -o moc_CInformationElement.cpp

moc_CInformationCollection.cpp: src/global.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/information/CInformationElement.h \
		src/information/informationformat.h \
		src/information/Path.h \
		src/information/IView.h \
		src/information/CInformationCollection.h
	C:/DevTools/Qt/qt/bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\information\CInformationCollection.h -o moc_CInformationCollection.cpp

moc_mainwindow.cpp: src/information/IHistoryListener.h \
		src/information/CInformationElementHistory.h \
		src/information/CInformationElement.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/information/informationformat.h \
		src/information/IView.h \
		src/gui/dialogs/optionsdialog.h \
		ui_IOptionsDialog.h \
		src/CTuxCardsConfiguration.h \
		src/fontsettings.h \
		src/gui/CSingleEntryView.h \
		src/gui/editor.h \
		src/global.h \
		src/gui/CTree.h \
		src/gui/dialogs/CPropertyDialog.h \
		ui_IPropertyDialog.h \
		src/gui/dialogs/iconselectordialog.h \
		src/gui/dialogs/searchdialog.h \
		src/gui/dialogs/searchlistitem.h \
		src/gui/dialogs/searchposition.h \
		src/gui/CTreeElement.h \
		src/information/CTreeInformationElement.h \
		src/information/Path.h \
		src/information/CInformationCollection.h \
		src/gui/RecentFileList.h \
		src/gui/dialogs/CPasswdDialog.h \
		ui_IPasswdDialog.h \
		src/gui/mainwindow.h
	C:/DevTools/Qt/qt/bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\gui\mainwindow.h -o moc_mainwindow.cpp

moc_editor.cpp: src/global.h \
		src/information/IView.h \
		src/information/IRemoveElementListener.h \
		src/information/CInformationElement.h \
		src/information/IParent.h \
		src/information/informationformat.h \
		src/fontsettings.h \
		src/gui/editor.h
	C:/DevTools/Qt/qt/bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\gui\editor.h -o moc_editor.cpp

moc_CTree.cpp: src/information/IView.h \
		src/information/IRemoveElementListener.h \
		src/gui/dialogs/CPropertyDialog.h \
		ui_IPropertyDialog.h \
		src/gui/dialogs/iconselectordialog.h \
		src/gui/dialogs/searchdialog.h \
		src/gui/dialogs/searchlistitem.h \
		src/gui/dialogs/searchposition.h \
		src/gui/CTreeElement.h \
		src/information/CTreeInformationElement.h \
		src/information/CInformationElement.h \
		src/information/IParent.h \
		src/information/informationformat.h \
		src/global.h \
		src/information/Path.h \
		src/information/CInformationCollection.h \
		src/fontsettings.h \
		src/CTuxCardsConfiguration.h \
		src/gui/CTree.h
	C:/DevTools/Qt/qt/bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\gui\CTree.h -o moc_CTree.cpp

moc_CSingleEntryView.cpp: src/information/IView.h \
		src/information/IRemoveElementListener.h \
		src/gui/editor.h \
		src/global.h \
		src/information/CInformationElement.h \
		src/information/IParent.h \
		src/information/informationformat.h \
		src/fontsettings.h \
		src/gui/CSingleEntryView.h
	C:/DevTools/Qt/qt/bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\gui\CSingleEntryView.h -o moc_CSingleEntryView.cpp

moc_BookmarkButton.cpp: src/information/Path.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/gui/BookmarkButton.h
	C:/DevTools/Qt/qt/bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\gui\BookmarkButton.h -o moc_BookmarkButton.cpp

moc_RecentFileList.cpp: src/gui/RecentFileList.h
	C:/DevTools/Qt/qt/bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\gui\RecentFileList.h -o moc_RecentFileList.cpp

moc_CTreeElement.cpp: src/information/CTreeInformationElement.h \
		src/information/CInformationElement.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/information/informationformat.h \
		src/global.h \
		src/information/Path.h \
		src/gui/CTreeElement.h
	C:/DevTools/Qt/qt/bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\gui\CTreeElement.h -o moc_CTreeElement.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_clean: compiler_moc_header_clean 



####### Compile

persister.o: src/persister.cpp src/persister.h \
		src/information/CInformationCollection.h \
		src/global.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/information/CInformationElement.h \
		src/information/informationformat.h \
		src/information/Path.h \
		src/information/IView.h \
		src/information/CTreeInformationElement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o persister.o src\persister.cpp

fontsettings.o: src/fontsettings.cpp src/fontsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fontsettings.o src\fontsettings.cpp

CTuxCardsConfiguration.o: src/CTuxCardsConfiguration.cpp src/CTuxCardsConfiguration.h \
		src/fontsettings.h \
		src/version.h \
		src/global.h \
		src/utilities/iniparser/configparser.h \
		src/utilities/iniparser/configgroup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CTuxCardsConfiguration.o src\CTuxCardsConfiguration.cpp

commandlineoptions.o: src/commandlineoptions.cpp src/commandlineoptions.h \
		src/CTuxCardsConfiguration.h \
		src/fontsettings.h \
		src/information/xmlpersister.h \
		src/information/CInformationCollection.h \
		src/global.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/information/CInformationElement.h \
		src/information/informationformat.h \
		src/information/Path.h \
		src/information/IView.h \
		src/information/CTreeInformationElement.h \
		src/information/htmlwriter.h \
		src/version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o commandlineoptions.o src\commandlineoptions.cpp

CFileEncryptionPasswordDialog.o: src/gui/dialogs/CFileEncryptionPasswordDialog.cpp src/gui/dialogs/CFileEncryptionPasswordDialog.h \
		src/global.h \
		ui_IFileEncryptionPasswordDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CFileEncryptionPasswordDialog.o src\gui\dialogs\CFileEncryptionPasswordDialog.cpp

main.o: src/main.cpp src/gui/mainwindow.h \
		src/information/IHistoryListener.h \
		src/information/CInformationElementHistory.h \
		src/information/CInformationElement.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/information/informationformat.h \
		src/information/IView.h \
		src/gui/dialogs/optionsdialog.h \
		ui_IOptionsDialog.h \
		src/CTuxCardsConfiguration.h \
		src/fontsettings.h \
		src/gui/CSingleEntryView.h \
		src/gui/editor.h \
		src/global.h \
		src/gui/CTree.h \
		src/gui/dialogs/CPropertyDialog.h \
		ui_IPropertyDialog.h \
		src/gui/dialogs/iconselectordialog.h \
		src/gui/dialogs/searchdialog.h \
		src/gui/dialogs/searchlistitem.h \
		src/gui/dialogs/searchposition.h \
		src/gui/CTreeElement.h \
		src/information/CTreeInformationElement.h \
		src/information/Path.h \
		src/information/CInformationCollection.h \
		src/gui/RecentFileList.h \
		src/gui/dialogs/CPasswdDialog.h \
		ui_IPasswdDialog.h \
		src/commandlineoptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src\main.cpp

CTreeElement.o: src/gui/CTreeElement.cpp src/gui/CTreeElement.h \
		src/information/CTreeInformationElement.h \
		src/information/CInformationElement.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/information/informationformat.h \
		src/global.h \
		src/information/Path.h \
		src/gui/dialogs/searchlistitem.h \
		src/gui/dialogs/searchposition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CTreeElement.o src\gui\CTreeElement.cpp

CTree.o: src/gui/CTree.cpp src/gui/CTree.h \
		src/information/IView.h \
		src/information/IRemoveElementListener.h \
		src/gui/dialogs/CPropertyDialog.h \
		ui_IPropertyDialog.h \
		src/gui/dialogs/iconselectordialog.h \
		src/gui/dialogs/searchdialog.h \
		src/gui/dialogs/searchlistitem.h \
		src/gui/dialogs/searchposition.h \
		src/gui/CTreeElement.h \
		src/information/CTreeInformationElement.h \
		src/information/CInformationElement.h \
		src/information/IParent.h \
		src/information/informationformat.h \
		src/global.h \
		src/information/Path.h \
		src/information/CInformationCollection.h \
		src/fontsettings.h \
		src/CTuxCardsConfiguration.h \
		src/icons/delete.xpm \
		src/icons/changeProperty.xpm \
		src/icons/addTreeElement.xpm \
		src/icons/upArrow.xpm \
		src/icons/downArrow.xpm \
		src/information/xmlpersister.h \
		src/utilities/CIconManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CTree.o src\gui\CTree.cpp

mainwindow.o: src/gui/mainwindow.cpp src/gui/mainwindow.h \
		src/information/IHistoryListener.h \
		src/information/CInformationElementHistory.h \
		src/information/CInformationElement.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/information/informationformat.h \
		src/information/IView.h \
		src/gui/dialogs/optionsdialog.h \
		ui_IOptionsDialog.h \
		src/CTuxCardsConfiguration.h \
		src/fontsettings.h \
		src/gui/CSingleEntryView.h \
		src/gui/editor.h \
		src/global.h \
		src/gui/CTree.h \
		src/gui/dialogs/CPropertyDialog.h \
		ui_IPropertyDialog.h \
		src/gui/dialogs/iconselectordialog.h \
		src/gui/dialogs/searchdialog.h \
		src/gui/dialogs/searchlistitem.h \
		src/gui/dialogs/searchposition.h \
		src/gui/CTreeElement.h \
		src/information/CTreeInformationElement.h \
		src/information/Path.h \
		src/information/CInformationCollection.h \
		src/gui/RecentFileList.h \
		src/gui/dialogs/CPasswdDialog.h \
		ui_IPasswdDialog.h \
		src/icons/lo16-app-tuxcards.xpm \
		src/icons/lo32-app-tuxcards.xpm \
		src/information/converter.h \
		src/persister.h \
		src/information/xmlpersister.h \
		src/information/htmlwriter.h \
		src/utilities/iniparser/configparser.h \
		src/utilities/iniparser/configgroup.h \
		src/utilities/strings.h \
		src/gui/BookmarkButton.h \
		src/gui/dialogs/CFileEncryptionPasswordDialog.h \
		ui_IFileEncryptionPasswordDialog.h \
		src/utilities/crypt/StringCrypter.h \
		src/version.h \
		src/Greetings.h \
		src/utilities/CIconManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src\gui\mainwindow.cpp

editor.o: src/gui/editor.cpp src/gui/editor.h \
		src/global.h \
		src/information/IView.h \
		src/information/IRemoveElementListener.h \
		src/information/CInformationElement.h \
		src/information/IParent.h \
		src/information/informationformat.h \
		src/fontsettings.h \
		src/CTuxCardsConfiguration.h \
		src/utilities/strings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editor.o src\gui\editor.cpp

CSingleEntryView.o: src/gui/CSingleEntryView.cpp src/gui/CSingleEntryView.h \
		src/information/IView.h \
		src/information/IRemoveElementListener.h \
		src/gui/editor.h \
		src/global.h \
		src/information/CInformationElement.h \
		src/information/IParent.h \
		src/information/informationformat.h \
		src/fontsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CSingleEntryView.o src\gui\CSingleEntryView.cpp

BookmarkButton.o: src/gui/BookmarkButton.cpp src/gui/BookmarkButton.h \
		src/information/Path.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BookmarkButton.o src\gui\BookmarkButton.cpp

RecentFileList.o: src/gui/RecentFileList.cpp src/gui/RecentFileList.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RecentFileList.o src\gui\RecentFileList.cpp

searchposition.o: src/gui/dialogs/searchposition.cpp src/gui/dialogs/searchposition.h \
		src/gui/CTreeElement.h \
		src/information/CTreeInformationElement.h \
		src/information/CInformationElement.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/information/informationformat.h \
		src/global.h \
		src/information/Path.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o searchposition.o src\gui\dialogs\searchposition.cpp

searchlistitem.o: src/gui/dialogs/searchlistitem.cpp src/gui/dialogs/searchlistitem.h \
		src/gui/dialogs/searchposition.h \
		src/gui/CTreeElement.h \
		src/information/CTreeInformationElement.h \
		src/information/CInformationElement.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/information/informationformat.h \
		src/global.h \
		src/information/Path.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o searchlistitem.o src\gui\dialogs\searchlistitem.cpp

searchdialog.o: src/gui/dialogs/searchdialog.cpp src/global.h \
		src/gui/dialogs/searchdialog.h \
		src/gui/dialogs/searchlistitem.h \
		src/gui/dialogs/searchposition.h \
		src/gui/CTreeElement.h \
		src/information/CTreeInformationElement.h \
		src/information/CInformationElement.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/information/informationformat.h \
		src/information/Path.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o searchdialog.o src\gui\dialogs\searchdialog.cpp

optionsdialog.o: src/gui/dialogs/optionsdialog.cpp src/gui/dialogs/optionsdialog.h \
		ui_IOptionsDialog.h \
		src/CTuxCardsConfiguration.h \
		src/fontsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optionsdialog.o src\gui\dialogs\optionsdialog.cpp

iconselectordialog.o: src/gui/dialogs/iconselectordialog.cpp src/gui/dialogs/iconselector.h \
		src/gui/dialogs/iconselectordialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iconselectordialog.o src\gui\dialogs\iconselectordialog.cpp

iconselector.o: src/gui/dialogs/iconselector.cpp src/global.h \
		src/gui/dialogs/iconselector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iconselector.o src\gui\dialogs\iconselector.cpp

CPropertyDialog.o: src/gui/dialogs/CPropertyDialog.cpp src/icons/blank.xpm \
		src/gui/dialogs/CPropertyDialog.h \
		ui_IPropertyDialog.h \
		src/gui/dialogs/iconselectordialog.h \
		src/global.h \
		src/information/CTreeInformationElement.h \
		src/information/CInformationElement.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/information/informationformat.h \
		src/CTuxCardsConfiguration.h \
		src/fontsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CPropertyDialog.o src\gui\dialogs\CPropertyDialog.cpp

CPasswdDialog.o: src/gui/dialogs/CPasswdDialog.cpp src/gui/dialogs/CPasswdDialog.h \
		src/global.h \
		ui_IPasswdDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CPasswdDialog.o src\gui\dialogs\CPasswdDialog.cpp

xmlpersister.o: src/information/xmlpersister.cpp src/information/xmlpersister.h \
		src/information/CInformationCollection.h \
		src/global.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/information/CInformationElement.h \
		src/information/informationformat.h \
		src/information/Path.h \
		src/information/IView.h \
		src/information/CTreeInformationElement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xmlpersister.o src\information\xmlpersister.cpp

Path.o: src/information/Path.cpp src/global.h \
		src/information/Path.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Path.o src\information\Path.cpp

informationformat.o: src/information/informationformat.cpp src/information/informationformat.h \
		src/information/format_none.xpm \
		src/information/format_ascii.xpm \
		src/information/format_rtf.xpm
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o informationformat.o src\information\informationformat.cpp

htmlwriter.o: src/information/htmlwriter.cpp src/information/htmlwriter.h \
		src/information/CInformationCollection.h \
		src/global.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/information/CInformationElement.h \
		src/information/informationformat.h \
		src/information/Path.h \
		src/information/IView.h \
		src/version.h \
		src/information/dot.xpm \
		src/information/space15.xpm
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o htmlwriter.o src\information\htmlwriter.cpp

CTreeInformationElement.o: src/information/CTreeInformationElement.cpp src/information/CTreeInformationElement.h \
		src/information/CInformationElement.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/information/informationformat.h \
		src/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CTreeInformationElement.o src\information\CTreeInformationElement.cpp

converter.o: src/information/converter.cpp src/information/converter.h \
		src/information/CInformationElement.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/information/informationformat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o converter.o src\information\converter.cpp

CInformationElementHistory.o: src/information/CInformationElementHistory.cpp src/global.h \
		src/information/CInformationElementHistory.h \
		src/information/CInformationElement.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/information/informationformat.h \
		src/information/IView.h \
		src/information/IHistoryListener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CInformationElementHistory.o src\information\CInformationElementHistory.cpp

CInformationElement.o: src/information/CInformationElement.cpp src/information/CInformationElement.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/information/informationformat.h \
		src/global.h \
		src/utilities/strings.h \
		src/gui/dialogs/searchlistitem.h \
		src/gui/dialogs/searchposition.h \
		src/gui/CTreeElement.h \
		src/information/CTreeInformationElement.h \
		src/information/Path.h \
		src/utilities/crypt/StringCrypter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CInformationElement.o src\information\CInformationElement.cpp

CInformationCollection.o: src/information/CInformationCollection.cpp src/information/CInformationCollection.h \
		src/global.h \
		src/information/IParent.h \
		src/information/IRemoveElementListener.h \
		src/information/CInformationElement.h \
		src/information/informationformat.h \
		src/information/Path.h \
		src/information/IView.h \
		src/information/CTreeInformationElement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CInformationCollection.o src\information\CInformationCollection.cpp

strings.o: src/utilities/strings.cpp src/utilities/strings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o strings.o src\utilities\strings.cpp

integers.o: src/utilities/integers.cpp src/utilities/integers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integers.o src\utilities\integers.cpp

CIconManager.o: src/utilities/CIconManager.cpp src/utilities/CIconManager.h \
		src/global.h \
		src/icons/fileopen.xpm \
		src/icons/filenew.xpm \
		src/icons/filesave.xpm \
		src/icons/fileprint.xpm \
		src/icons/exit.xpm \
		src/icons/addTreeElement.xpm \
		src/icons/changeProperty.xpm \
		src/icons/delete.xpm \
		src/icons/lock.xpm \
		src/icons/unlock.xpm \
		src/icons/find.xpm \
		src/icons/redo.xpm \
		src/icons/undo.xpm \
		src/icons/editcut.xpm \
		src/icons/editcopy.xpm \
		src/icons/editpaste.xpm \
		src/icons/editentrycolor.xpm \
		src/icons/editentrysubtreecolor.xpm \
		src/icons/text_bold.xpm \
		src/icons/text_italic.xpm \
		src/icons/text_under.xpm \
		src/icons/text_color.xpm \
		src/icons/text_left.xpm \
		src/icons/text_center.xpm \
		src/icons/text_right.xpm \
		src/icons/text_block.xpm \
		src/icons/upArrow.xpm \
		src/icons/downArrow.xpm \
		src/icons/back.xpm \
		src/icons/forward.xpm \
		src/icons/locksm.xpm \
		src/icons/unlocksm.xpm \
		src/icons/filelock.xpm \
		src/icons/fileunlock.xpm
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CIconManager.o src\utilities\CIconManager.cpp

StringCrypter.o: src/utilities/crypt/StringCrypter.cpp src/utilities/crypt/BlowFish.h \
		src/utilities/crypt/MD5.h \
		src/utilities/crypt/StringCrypter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StringCrypter.o src\utilities\crypt\StringCrypter.cpp

MD5.o: src/utilities/crypt/MD5.cpp src/utilities/crypt/MD5.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MD5.o src\utilities\crypt\MD5.cpp

BlowFish.o: src/utilities/crypt/BlowFish.cpp src/global.h \
		src/utilities/crypt/BlowFish.h \
		src/utilities/crypt/BlowFish2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BlowFish.o src\utilities\crypt\BlowFish.cpp

configparser.o: src/utilities/iniparser/configparser.cpp src/global.h \
		src/utilities/iniparser/configparser.h \
		src/utilities/iniparser/configgroup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configparser.o src\utilities\iniparser\configparser.cpp

configgroup.o: src/utilities/iniparser/configgroup.cpp src/global.h \
		src/utilities/iniparser/configgroup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configgroup.o src\utilities\iniparser\configgroup.cpp

moc_searchdialog.o: moc_searchdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_searchdialog.o moc_searchdialog.cpp

moc_optionsdialog.o: moc_optionsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_optionsdialog.o moc_optionsdialog.cpp

moc_iconselectordialog.o: moc_iconselectordialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_iconselectordialog.o moc_iconselectordialog.cpp

moc_iconselector.o: moc_iconselector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_iconselector.o moc_iconselector.cpp

moc_CPropertyDialog.o: moc_CPropertyDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CPropertyDialog.o moc_CPropertyDialog.cpp

moc_CPasswdDialog.o: moc_CPasswdDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CPasswdDialog.o moc_CPasswdDialog.cpp

moc_CFileEncryptionPasswordDialog.o: moc_CFileEncryptionPasswordDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CFileEncryptionPasswordDialog.o moc_CFileEncryptionPasswordDialog.cpp

moc_CInformationElement.o: moc_CInformationElement.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CInformationElement.o moc_CInformationElement.cpp

moc_CInformationCollection.o: moc_CInformationCollection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CInformationCollection.o moc_CInformationCollection.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_editor.o: moc_editor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editor.o moc_editor.cpp

moc_CTree.o: moc_CTree.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CTree.o moc_CTree.cpp

moc_CSingleEntryView.o: moc_CSingleEntryView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CSingleEntryView.o moc_CSingleEntryView.cpp

moc_BookmarkButton.o: moc_BookmarkButton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_BookmarkButton.o moc_BookmarkButton.cpp

moc_RecentFileList.o: moc_RecentFileList.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_RecentFileList.o moc_RecentFileList.cpp

moc_CTreeElement.o: moc_CTreeElement.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CTreeElement.o moc_CTreeElement.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

